docker:
  image: "redis"
  tag: "7.2.5"
  interval: 5          # Interval for execution
  interval_unit: "s"    # Time unit for interval ("s" for seconds, "m" for minutes, "h" for hours)
  concurrent: false
  timeout: 10           # Timeout for Docker container execution
  timeout_unit: "s"     # Time unit for timeout ("s" for seconds, "m" for minutes, "h" for hours)
