name: lint check for dionysos

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2
          working-directory: ${{ github.workspace }}
          args: --timeout 3m --verbose
          only-new-issues: true